services:
  - type: web
    name: mobogo-api
    runtime: node
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: node dist/main.js
    envVarGroups: []
    autoDeploy: true
