FROM node:20-alpine

RUN apk add --no-cache dumb-init openssl

WORKDIR /app

COPY package*.json ./
COPY prisma ./prisma/

RUN npm install && npx prisma generate

COPY . .

EXPOSE 8000

ENTRYPOINT ["dumb-init", "--"]
CMD ["npm", "run", "start:dev"]