user  nginx;
worker_processes  auto;

events {
    worker_connections  1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout  65;

    # Limitador de taxa (Rate Limit) da API
    limit_req_zone $binary_remote_addr zone=api:10m rate=100r/m;

    server {
        listen       80;
        server_name  localhost;

        location /api/ {
            limit_req zone=api burst=20 nodelay;
            limit_req_status 429;
            
            # Redireciona corretamente para o serviço "api" na porta 8000
            proxy_pass http://api:8000;
            
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Resposta padrão para qualquer outra rota não contida no /api/
        location / {
            return 404;
        }
    }
}