export enum Permission {
  USER_CREATE_WITH_PHONE = 'user:create:phone',
  USER_CREATE_WITHOUT_PHONE = 'user:create:no_phone',
  USER_BLOCK = 'user:block',
  USER_ACTIVATE = 'user:activate',
  USER_VIEW_ALL = 'user:view:all',
  AGENT_CREATE = 'agent:create',
  AGENT_DELEGATE = 'agent:delegate',
  AGENT_DEACTIVATE = 'agent:deactivate',
  TICKET_CREATE = 'ticket:create',
  TICKET_CANCEL = 'ticket:cancel',
  TICKET_SCAN = 'ticket:scan',
  TICKET_TRANSFER = 'ticket:transfer',
  TICKET_VIEW_HISTORY = 'ticket:view:history',
  TICKET_SET_VALUE = 'ticket:set:value',
  TICKET_SET_LIMIT = 'ticket:set:limit',
  WALLET_TOPUP = 'wallet:topup',
  WALLET_WITHDRAW = 'wallet:withdraw',
  WALLET_VIEW = 'wallet:view',
  LOCATION_TRACK = 'location:track',
  LOCATION_VIEW_ALL = 'location:view:all',
  REPORT_VIEW_OWN = 'report:view:own',
  REPORT_VIEW_ALL = 'report:view:all',
  REPORT_EXPORT = 'report:export',
}

export const ROLE_PERMISSIONS: Record<string, Permission[]> = {
  ADMIN: Object.values(Permission),
  AGENT: [
    Permission.USER_CREATE_WITH_PHONE,
    Permission.USER_CREATE_WITHOUT_PHONE,
    Permission.TICKET_CREATE,
    Permission.TICKET_SCAN,
    Permission.REPORT_VIEW_OWN,
  ],
  DRIVER: [
    Permission.TICKET_SCAN,
    Permission.TICKET_CANCEL,
    Permission.TICKET_VIEW_HISTORY,
    Permission.REPORT_VIEW_OWN,
    Permission.LOCATION_TRACK,
  ],
  PASSENGER: [
    Permission.WALLET_TOPUP,
    Permission.WALLET_WITHDRAW,
    Permission.WALLET_VIEW,
    Permission.TICKET_TRANSFER,
    Permission.TICKET_VIEW_HISTORY,
  ],
  CLIENT: [
    Permission.USER_CREATE_WITH_PHONE,
    Permission.TICKET_VIEW_HISTORY,
    Permission.REPORT_VIEW_ALL,
    Permission.REPORT_EXPORT,
  ],
  LOTADOR: [Permission.TICKET_SCAN, Permission.LOCATION_VIEW_ALL],
};
